### PR TITLE
missing completion handler call

### PR DESCRIPTION
**Pull request by BlixLT**
It looks like to be a bug here - if a method has a completion block I suppose it to be called before returning from the method (always or at least in most circumstances).

### CODE REVIEW

**Comment by mentrena** [comment]
That looks good. Could you maybe add a case to `SyncError` in `CloudKitSynchronizer.swift` and return that error here?

**Comment by BlixLT** [comment]
Something like that?

**Comment by mentrena** [comment]
Thanks! Let me know if you need me to do a release, otherwise I might try to look at the other issues before releasing.

**Comment by BlixLT** [comment]
No need (for me) to do a release just with this fix - the other issues I submitted are more important.

**Pull request merged**
